apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w1gmmg0l2-python
  janus-idp.io/tekton: w1gmmg0l2-python
  backstage.io/kubernetes-id: w1gmmg0l2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w1gmmg0l2-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
